name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (for building Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t fitness-tracker-app:latest .

      # 4. Run tests inside container
      - name: Run Pytest and Coverage in container
        run: |
          docker run --rm fitness-tracker-app:latest coverage run --source=src -m pytest
          docker run --rm fitness-tracker-app:latest coverage report